dbt_project:
  outputs:
    dev:
      dataset: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/alexandre-colmenero/Estudo/dbt/dbt_env/dbt_project/secrets/bigquery.json
      location: US
      method: service-account
      priority: interactive
      project: estudos-414618
      threads: 1
      type: bigquery

    ci:  # Ambiente do GitHub Actions
      dataset: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: $HOME/gcp-key.json
      location: US
      method: service-account
      priority: interactive
      project: estudos-414618
      threads: 1
      type: bigquery

  target: dev  # Define "dev" como padrão para ambiente local
